#!/bin/bash

#test 1 archive present
if [ ! -f ./prog3.tgz ]; then
    echo "Project archive not found in current directory. Submission will not be graded."
    exit 1
fi

gtar zxf prog3.tgz

#test 2 make 
(make) >/dev/null
made=$?
if [ "$made" -ne "0" ]; then
	echo -e "Make returned an error. Submission will not be graded."
	exit 1
fi

#test 3 encode present
if [ ! -f ./encode ]; then
    echo "encode not generated by make. Submission will not be graded."
    exit 1
fi

#test 4 decode present
if [ ! -f ./decode ]; then
    echo "main.o not generated by make. Submission will not be graded."
    exit 1
fi


echo "Submission will be graded successfully. Please be aware this does not test your submission for functionality, only that the autograder will run successfully."
